# Generated by Django 2.2 on 2020-11-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VRapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(default=100, upload_to='static/img', verbose_name='Изображение'),
        ),
    ]
